### ISSUE TITLE
RFE: Fix the install script as it gives an error due to dependency on Kind

### ISSUE THREAD

**Issue by praseedasathaye** [crossplane-contrib/back-stack#45]
Here is the message "./local-install.sh
./local-install.sh: line 6: kind: command not found"

**Comment by djeremiah** [comment]
The local-install *does* have a dependency on kind. 

Is the RFE here to improve validation in the install script, improve docs around prereqs, or implement an alternative installer that's less opinionated?

I think all three are worthwhile, but wanted to be sure I understand your intent.

**Comment by djeremiah** [comment]
#38 Has addressed the first issue. We're in progress of moving to a new, separate repo. We can create separate issues for the other two in there.

**Comment by djeremiah** [comment]
https://github.com/back-stack/showcase/issues/2
https://github.com/back-stack/showcase/issues/3
